# Remember to change the CHANGE_ME strings.
services:
  bot:
    build: .
    # image: ghcr.io/dhedegaard/ye-olde-link-detector:main
    restart: unless-stopped
    environment:
      - TOKEN=${TOKEN:-CHANGE_ME}
      - CONNECTION_STRING=${CONNECTION_STRING:-Host=db; Port=5432; Username=postgres; Password=CHANGE_ME; Database=db}
    depends_on:
      db:
        condition: service_started
    dns:
      - 8.8.8.8
      - 8.8.4.4

  db:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-CHANGE_ME}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_DB=${POSTGRES_DB:-db}
    volumes:
      - db-volume:/var/lib/postgresql/data

volumes:
  db-volume:
